---
name: Poc example using self-hosted runner of ec2
on:
  push:
    branches: [main]

env:
  AWS_REGION: eu-central-1
  S3_BUCKET: test-1001-bucket
jobs:
  deploy:
    name: List S3 contents
    runs-on: self-hosted
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout (Checkout (Git clone the repository))
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}
          role-session-name: OIDC-Github-action-role
          aws-region: ${{ env.AWS_REGION }}
      - name: List s3 bucket files
        run: |
          aws s3 ls s3://${{ env.S3_BUCKET }}
